In [25]:
# Bagged Decision Trees for Classification
import numpy as np
from sklearn import metrics
from pandas import read_csv
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
#filename = '/content/pima-indians-diabetes.data.csv'

names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = read_csv("C:/Users/Vikas Srivastava/Desktop/ExcelR/Latest DS Material/Day 25-Feature Engineering/pima-indians-diabetes.data.csv", names=names)
array = dataframe.values
X = array[:,0:8]
Y = array[:,8]

In [10]:
dataframe

preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]

In [31]:
seed = 7

kfold = KFold(n_splits=10)

cart = DecisionTreeClassifier()

num_trees = 100
model = BaggingClassifier(base_estimator=cart, n_estimators=num_trees, random_state=seed)

results = cross_val_score(model, X, Y, cv=5)
print(results.mean())

0.7734827264239029


In [32]:
results

array([0.75974026, 0.75974026, 0.76623377, 0.83006536, 0.75163399])

In [17]:
from sklearn.model_selection import cross_val_score , KFold
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=123)

In [19]:
bg_clf = BaggingClassifier(base_estimator=cart, n_estimators=num_trees, random_state=seed)
bg_clf.fit(X_train, y_train)

BaggingClassifier(base_estimator=DecisionTreeClassifier(), n_estimators=100,
                  random_state=7)

In [44]:
### for train data
import pandas as pd
y_pred_train = bg_clf.predict(X_train)

metrics.accuracy_score( y_train, y_pred_train)

### for test data
y_pred_test = bg_clf.predict(X_test)

# print('Root Mean Squared Error (RMSE) for test data:', np.sqrt(metrics.mean_squared_error(y_test, y_pred_test)))
# print('R2 for test data :',metrics.r2_score(y_test, y_pred_test))

In [48]:
bg_clf.predict_proba(X_test)

array([[0.09, 0.91],
       [0.59, 0.41],
       [0.25, 0.75],
       [1.  , 0.  ],
       [0.88, 0.12],
       [0.29, 0.71],
       [0.32, 0.68],
       [0.27, 0.73],
       [0.21, 0.79],
       [0.24, 0.76],
       [0.2 , 0.8 ],
       [0.79, 0.21],
       [0.84, 0.16],
       [0.42, 0.58],
       [0.29, 0.71],
       [0.99, 0.01],
       [0.56, 0.44],
       [1.  , 0.  ],
       [0.99, 0.01],
       [0.48, 0.52],
       [0.26, 0.74],
       [0.95, 0.05],
       [0.5 , 0.5 ],
       [0.1 , 0.9 ],
       [0.13, 0.87],
       [0.8 , 0.2 ],
       [0.96, 0.04],
       [0.72, 0.28],
       [0.62, 0.38],
       [0.29, 0.71],
       [0.94, 0.06],
       [0.32, 0.68],
       [0.26, 0.74],
       [0.74, 0.26],
       [0.72, 0.28],
       [0.97, 0.03],
       [0.31, 0.69],
       [0.87, 0.13],
       [0.91, 0.09],
       [0.8 , 0.2 ],
       [0.97, 0.03],
       [0.93, 0.07],
       [0.92, 0.08],
       [0.62, 0.38],
       [1.  , 0.  ],
       [0.14, 0.86],
       [0.26, 0.74],
       [0.99,

In [46]:
tree_train_pred = pd.DataFrame( { 'actual':  y_test,
                            'pred': bg_clf.predict(X_test)} )
tree_train_pred


actual  pred
0       1.0   1.0
1       0.0   0.0
2       0.0   1.0
3       0.0   0.0
4       0.0   0.0
..      ...   ...
149     0.0   0.0
150     1.0   1.0
151     0.0   0.0
152     0.0   0.0
153     0.0   0.0

[154 rows x 2 columns]

In [3]:
dataframe.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [4]:
# from google.colab import drive
# drive.mount('/content/drive')

In [38]:
# Random Forest Classification
from pandas import read_csv
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

X = array[:,0:8]
Y = array[:,8]
num_trees = 100
max_features = 3
kfold = KFold(n_splits=10)
model = RandomForestClassifier(n_estimators=num_trees, max_features=max_features)
results = cross_val_score(model, X, Y, cv=kfold)
print(results.mean())

0.7668318523581681


In [39]:
results

array([0.67532468, 0.83116883, 0.72727273, 0.67532468, 0.77922078,
       0.80519481, 0.84415584, 0.87012987, 0.68421053, 0.77631579])

In [6]:
# AdaBoost Classification
from pandas import read_csv
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import AdaBoostClassifier

# filename = 'pima-indians-diabetes.data.csv'
# names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
# dataframe = read_csv(filename, names=names)
# array = dataframe.values

# X = array[:,0:8]
# Y = array[:,8]

num_trees = 10
seed=7
kfold = KFold(n_splits=10)
model = AdaBoostClassifier(n_estimators=num_trees, random_state=seed)
results = cross_val_score(model, X, Y, cv=kfold)
print(results.mean())


0.7525974025974026


In [7]:
# Stacking Ensemble for Classification
from pandas import read_csv
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier

# filename = '/content/pima-indians-diabetes.data.csv'
# names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
# dataframe = read_csv(filename, names=names)
# array = dataframe.values
# X = array[:,0:8]
# Y = array[:,8]
kfold = KFold(n_splits=10)



# create the sub models
estimators = []

model1 = LogisticRegression(max_iter=500)
estimators.append(('logistic', model1))

model2 = DecisionTreeClassifier()
estimators.append(('cart', model2))

model3 = SVC()
estimators.append(('svm', model3))

# create the ensemble model
ensemble = VotingClassifier(estimators)
results = cross_val_score(ensemble, X, Y, cv=kfold)
print(results.mean())

0.768215994531784


In [8]:
estimators

[('logistic', LogisticRegression(max_iter=500)),
 ('cart', DecisionTreeClassifier()),
 ('svm', SVC())]

In [9]:
# estimators = []
# model1 = LogisticRegression(max_iter=500)
# estimators.append(('logistic', model1))
# model2 = DecisionTreeClassifier()
# estimators.append(('cart', model2))
# model3 = SVC()
# estimators.append(('svm', model3))
# estimators